name: ogg_record_player
version: 2.0.0
description: "An ogg opus file player and recorder for flutter."
homepage: https://github.com/SunnatilloShavkatov/ogg_record_player

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  system_clock: ^3.0.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  analysis_lints: ^1.1.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SwiftOggOpusPlayerPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: SwiftOggOpusPlayerPlugin
        sharedDarwinSource: true
      android:
        package: uz.plugin.ogg_opus_player
        pluginClass: OggOpusPlayerPlugin
