// swift-tools-version: 5.9
import PackageDescription

let package = Package(
  name: "ogg_record_player",
  platforms: [
    .iOS("15.0"),
    .macOS("10.15"),
  ],
  products: [
    .library(name: "ogg-record-player", targets: ["ogg_record_player"]),
  ],
  dependencies: [
    // Required by Flutter >= 3.44 SwiftPM integration; the real package is
    // generated by the flutter tool next to the symlinked plugin package.
    .package(name: "FlutterFramework", path: "../FlutterFramework"),
  ],
  targets: [
    .binaryTarget(name: "libogg", path: "Frameworks/libogg.xcframework"),
    .binaryTarget(name: "libopus", path: "Frameworks/libopus.xcframework"),
    .binaryTarget(name: "libopusenc", path: "Frameworks/libopusenc.xcframework"),
    .binaryTarget(name: "libopusfile", path: "Frameworks/libopusfile.xcframework"),
    .target(
      name: "ogg_record_player_c",
      dependencies: [
        "libogg",
        "libopus",
        "libopusenc",
        "libopusfile",
      ],
      path: "Sources/ogg_record_player_c",
      publicHeadersPath: "include",
      cSettings: [
        .headerSearchPath("."),
        .headerSearchPath("include"),
      ]
    ),
    .target(
      name: "ogg_record_player",
      dependencies: [
        .product(name: "FlutterFramework", package: "FlutterFramework"),
        "ogg_record_player_c",
      ],
      path: "Sources/ogg_record_player",
      linkerSettings: [
        .linkedFramework("AVFoundation"),
        .linkedFramework("AudioToolbox"),
        .linkedFramework("CoreAudio"),
        .linkedFramework("UIKit", .when(platforms: [.iOS])),
        .linkedFramework("AppKit", .when(platforms: [.macOS])),
      ]
    ),
  ]
)
